# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3963e98c0cebc9ee13e7c0ef366163630f3628f166250f2ae3337864cd0058604e969cf3794276656b787806cec69c94a6c0853e8bc1188b0858e906ce041e

test:
  secret_key_base: d8fab97cc20b6b7b0d01e6556d762335e6b027f9aaa891f7a712c15605d22bbaa1f07f75a83a7d77b34d254a1d0bd4077865351acdd11b9e521fb90dbd1a705f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
